# Generated by Django 5.2.7 on 2026-04-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionevent',
            name='object_class',
            field=models.CharField(choices=[('trash', 'Trash'), ('food', 'Food Remains'), ('animal', 'Animal'), ('bottle', 'Plastic Bottle'), ('littering', 'Littering Behaviors')], max_length=20),
        ),
    ]
