# Generated by Django 6.0.5 on 2026-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_detectionevent_object_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='cropped_object',
            field=models.ImageField(blank=True, help_text='Tight crop around the detected object', null=True, upload_to='detections/cropped/'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='full_frame',
            field=models.ImageField(blank=True, help_text='Full camera frame at the moment of detection', null=True, upload_to='detections/full_frames/'),
        ),
    ]
