# Generated by Django 5.2.1 on 2026-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alertrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='synced_to_cloud',
            field=models.BooleanField(default=False),
        ),
    ]
