# Generated by Django 5.2.1 on 2026-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_detectionevent_synced_to_cloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionevent',
            name='object_class',
            field=models.CharField(choices=[('trash', 'Trash'), ('food', 'Food Remains'), ('animal', 'Animal'), ('bottle', 'Plastic Bottle')], max_length=20),
        ),
    ]
